version: '3'

services:
    discord-bot:
        image: discord-bot
        build:
            dockerfile: ./bots/discord/Dockerfile
            context: .
    slack-bot:
        image: slack-bot
        build:
            dockerfile: ./bots/slack/Dockerfile
            context: .
    telegram-bot:
        image: telegram-bot
        build:
            dockerfile: ./bots/telegram/Dockerfile
            context: .
