[[code_responses]]
query = "What is 1 + 1?"
response = """
def answer_question(df: pd.DataFrame) -> int:
    # Calculate result
    result = 1 + 1
    # Return result
    return result
"""

[[code_responses]]
query = "What is the average X of Y?"
response = """
def answer_question(df: pd.DataFrame) -> float:
    # Clean results and remove outliers
    df = ...
    # Calculate average
    result = df['X'].mean()
    # Return average
    return result
"""

[[code_responses]]
query = "Plot a chart of X over time."
response = """
def answer_question(df: pd.DataFrame) -> plotly.graph_objs.Figure:
    # Clean results and remove outliers
    df = ...
    # Convert types if necessary
    df['date'] = pd.to_datetime(df['timestamp'])
    # Create chart
    fig = px.line(df, x='date', y='X')
    # Return chart
    return fig
"""

[[code_responses]]
query = "Perform exploratory data analysis (EDA)."
response = """
def answer_question(df: pd.DataFrame) -> List[plotly.graph_objs.Figure]:
    # Clean results and remove outliers
    df = ...
    # Create charts
    histogram = px.histogram(df, x='X')
    scatter = px.scatter(df, x='X', y='Y')
    line = px.line(df, x='date', y='X')
    # Return charts
    return [histogram, scatter, line]
"""

[[code_responses]]
query = "What data is available?"
response = """
def answer_question(df: pd.DataFrame) -> pd.DataFrame:
    # Clean results and remove outliers
    df = ...
    # Create summary statistics
    result = df.describe()
    # Return summary statistics
    return result
"""

[[code_responses]]
query = "What is the distribution of X?"
response = """
def answer_question(df: pd.DataFrame) -> plotly.graph_objs.Figure:
    # Clean results and remove outliers
    df = ...
    # Create chart
    fig = px.histogram(df, x='X')
    # Return chart
    return fig
"""
